<?php namespace Datwork\Webhooks;

use Backend\Facades\BackendAuth;
use Illuminate\Support\Facades\Event;
use System\Classes\PluginBase;
use System\Classes\SettingsManager;

class Plugin extends PluginBase
{
    public function registerComponents()
    {

    }

    public function registerSettings()
    {
        return [
            'settings' => [
                'label' => 'datwork.webhooks::lang.setting.title',
                'description' => 'datwork.webhooks::lang.setting.desc',
                'category' => SettingsManager::CATEGORY_SYSTEM,
                'icon' => 'icon-git',
                'class' => 'Datwork\Webhooks\Models\Settings',
                'order' => 500,
                'keywords' => 'git webhooks',
                'permissions' => ['datwork.webhooks.access_settings']
            ]
        ];
    }

    public function registerSchedule($schedule)
    {

    }

    public function registerPermissions()
    {
        return [
            'datwork.webhooks.access_settings' => [
                'label' => 'datwork.webhooks::lang.setting.title',
                'tab' => 'datwork.webhooks::lang.plugin.name',
                'order' => 200,
                'roles' => ['developer']
            ]
        ];
    }

    public function registerReportWidgets()
    {
        return [
            'Datwork\Webhooks\ReportWidgets\GitHooks' => [
                'label' => 'GitHooks',
                'context' => 'dashboard',
                'permissions' => [
                    'datwork.webhooks.access_settings',
                ],
            ]
        ];
    }

    public function boot()
    {//如果没有权限就移除 GitHooks

        Event::listen('system.reportwidgets.extendItems', function ($manager) {
            if (BackendAuth::getUser()) {
                if (!BackendAuth::getUser()->hasAccess(['datwork.webhooks.access_settings'])) {
                    $manager->removeReportWidget('Datwork\Webhooks\ReportWidgets\GitHooks');
                }
            }
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }


}
